### ISSUE TITLE
功能

### ISSUE THREAD

**Issue by CoderShmily** [lwhldy/CodeBuilder#1]
大佬问一下，有开关可以设置 只改类名  方法名  不修改属性的吗。因为文件太多了，后边修改属性的时候总是崩溃

**Comment by lwhldy** [comment]
可以，->参见说明文档8、9条
8. 只修改类名的文件名或类名/only_change_clsname_names （可选）
深度读取，只修改类名，不修改内部属性与方法，这个优先级最低，如果之前的条件包含了本参数中的路径，则不生效
9. 只修改类名的文件夹/文件路径/only_change_clsname_pathes （可选）
深度读取，只修改类名，不修改内部属性与方法的文件名，这个优先级最低，如果之前的条件包含了本参数中的路径 则不生效

**Comment by CoderShmily** [comment]
大佬，因为涉及的文件比较多，所以是想只改类名和方法名的 （ 属性总是崩溃，因为是闪退有时候都来不及发现是哪个文件的问题）。 但是看8-9条都是方法名和属性一起关了，不能单独设置。有没有别的方法可以解决呢
![image](https://user-images.githubusercontent.com/13568251/162874849-5221711c-0fdd-4286-8a55-a2c4803952a6.png)

**Comment by CoderShmily** [comment]
![image](https://user-images.githubusercontent.com/13568251/162910556-86be5a1b-0d46-449c-a99c-aa2159804464.png)
![image](https://user-images.githubusercontent.com/13568251/162910712-65cf49b2-3dd4-4398-ab80-3959526d5181.png)

![image](https://user-images.githubusercontent.com/13568251/162910555-6a5e5a00-a6b3-4b67-9977-b2a4cf483d2c.png)
就这一个文件属性替换能一直等半个小时没反应，也不知道是卡在哪一步了

**Comment by lwhldy** [comment]
文件多的话，时间成本是幂次增加的（程序需要将所有相关联的类都解析，解析次数：文件count*文件count），你可以考虑将相关联的类文件拆解成多份来跑，如果能定位出问题的文件但又没有具体报错，建议使用3、4条说明直接规避掉，如果还是不行，最后还有个办法是将源码邮件发我，我来定位问题并修复然后更新软件版本，你自己酌情考虑。

**Comment by CoderShmily** [comment]
好的大佬，我找了一台机器，软件运行后专门在录屏，找到让软件闪退的文件 都先删除 （配置文件我设置了"copy_only_names": "SearchTabModel","only_change_clsname_names": "SearchTabModel", 在运行的时候还是会卡到  正在进行属性名替换，位置：SearchTabModel 进度：523/1854 这个文件，可能是没设置对，我先删了文件）。

**Comment by CoderShmily** [comment]
![image](https://user-images.githubusercontent.com/13568251/163095362-2bd774df-d0bc-4666-88e8-446c468b4f9f.png)
大佬 现在就卡在SearchTabModel，文件删了又卡在 上边那两个文件，反正就是521-523 就运行不下去了。卡了以后基本一小时都不会动。可不可以只把属性替换做个开关可以关掉，让项目所有文件可以实现  类名和方法名替换 。或者有什么别的方法可以处理这个

**Comment by CoderShmily** [comment]
![image](https://user-images.githubusercontent.com/13568251/163121924-8c8b1c50-4c0d-41c5-bb8e-25a5654ad0cb.png)
就是删了最后一个，他就往前面的文件卡。。这

**Comment by lwhldy** [comment]
那问题可能不是出现在显示的这些文件上面，这一步是关联代码最多的地方，只能通过拿到源码测试来解决问题了。

**Comment by CoderShmily** [comment]
大佬留个邮箱联系吧，feedback_iOS@yeah.com 这个邮箱发邮件被退回来了，说所属域名不存在，邮件无法送达。

**Comment by lwhldy** [comment]
feedback_ios@yeah.net，不好意思，写错了
